<a href="https://colab.research.google.com/github/gadichandu3-prog/inership_datadrame-_import/blob/main/covariance%20and%20correlation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Covariance**
covariance tells you whether two variables move together.

positive covariance --> X variable increases y also increases

Negative covariance --> X variable increases y also decreases

Zero covariance --> no relation b/w the variables

NOTE:: covariance shows only direction not strength

In [1]:
import pandas as pd

data = {
    "Study_Hours": [2.9, 5.8, 4.7, 4.0, 1.8, 1.8, 1.3, 5.3, 4.0, 4.5],
    "Marks": [27.0, 61.0, 45.0, 38.0, 19.0, 8.0, 4.0, 50.0, 35.0, 47.0]
}

df = pd.DataFrame(data)
print(df)


   Study_Hours  Marks
0          2.9   27.0
1          5.8   61.0
2          4.7   45.0
3          4.0   38.0
4          1.8   19.0
5          1.8    8.0
6          1.3    4.0
7          5.3   50.0
8          4.0   35.0
9          4.5   47.0


In [2]:
df.cov() # find a covariance , if the diagonal has positive values, range is (-infinity ,+ infinity)

Study_Hours       Marks
Study_Hours     2.481000   28.906667
Marks          28.906667  348.711111

**Correlation**

Directoon + shows how strong the relationship is it shows +1 perfect positive relationship it shows -1 perfect negative relationship

In [3]:
df.corr() # find a correlation, it shows the strength and relationship, range is (-1,1)

Study_Hours    Marks
Study_Hours      1.00000  0.98277
Marks            0.98277  1.00000

In [4]:
df.var()

Study_Hours      2.481000
Marks          348.711111
dtype: float64

In [5]:
import pandas as pd

data = {
    "Temperature": [34, 24, 34, 12, 67, 78, 89],
    "Sunny": [50, 45, 36, 56, 78, 89, 78]
}

df = pd.DataFrame(data)
print(df)


   Temperature  Sunny
0           34     50
1           24     45
2           34     36
3           12     56
4           67     78
5           78     89
6           89     78


In [6]:
df.var()

Temperature    867.571429
Sunny          397.571429
dtype: float64

In [7]:
df.corr()

Temperature     Sunny
Temperature     1.000000  0.830515
Sunny           0.830515  1.000000

In [8]:
df.cov()

Temperature       Sunny
Temperature   867.571429  487.761905
Sunny         487.761905  397.571429

In [9]:
data= {
    "temp": [30,32,34,35,36],   # negative correlation
    "humidity":[40,39,34,28,27]
}
df=pd.DataFrame(data)
df


temp  humidity
0    30        40
1    32        39
2    34        34
3    35        28
4    36        27

In [10]:
df.cov()

temp  humidity
temp       5.8     -13.8
humidity -13.8      36.3

In [11]:
df.var()

temp         5.8
humidity    36.3
dtype: float64

In [12]:
df.corr()

temp  humidity
temp      1.000000 -0.951068
humidity -0.951068  1.000000

**Normalization**

Normalization is a technique used to scale the values of features into a small range, usually 0 to 1. It makes all features equal in scale to the model does not get confused by big and small numbers.

**use**

it have different ranges big numbers dominate small numbers models work better when all values are in same range training becomes faster and more accurate

In [13]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler
import pandas as pd

In [14]:
import pandas as pd
s=pd.Series([1000,2000,3000,4000,9000])
s

0    1000
1    2000
2    3000
3    4000
4    9000
dtype: int64

In [15]:
s.min()

1000

In [16]:
s.max()

9000

In [17]:
sn=(s-s.min())/(s.max()-s.min())
sn

0    0.000
1    0.125
2    0.250
3    0.375
4    1.000
dtype: float64

In [18]:
sn=MinMaxScaler().fit_transform(s.values.reshape(-1,1))
print(sn)

[[0.   ]
 [0.125]
 [0.25 ]
 [0.375]
 [1.   ]]


In [19]:
data= {
    "temp": [30,32,34,35,36],
    "humidity":[40,39,34,28,27]
}
df=pd.DataFrame(data)
df

temp  humidity
0    30        40
1    32        39
2    34        34
3    35        28
4    36        27

In [20]:
norm_data=MinMaxScaler().fit_transform(df) # to normalize the code
n_df= pd.DataFrame(norm_data,columns=df.columns) # it gives the data in an array
norm_data

array([[0.        , 1.        ],
       [0.33333333, 0.92307692],
       [0.66666667, 0.53846154],
       [0.83333333, 0.07692308],
       [1.        , 0.        ]])

In [21]:
n_df # it displays in a structured format

temp  humidity
0  0.000000  1.000000
1  0.333333  0.923077
2  0.666667  0.538462
3  0.833333  0.076923
4  1.000000  0.000000

**Standardization**

Standardization or Z score normalization is a scaler technique that transforms data so that : Mean = 0,standard deviation= 1. It shows how far each value is from the mean.

**Use**

makes data centered around zero
works well when data follows a normal distribution
less affected by outliers compared to normalization
Helps the model learn more smoothly

**Algorithms**

lOgistic Regression pCA sVM linear regression neural Networks

**range is -->(-infini
ty,+infinity)**

z= (x=mue)/sigma, mue=mean, sigma= standard deviation

In [22]:
import pandas as pd
s=pd.Series([1000,2000,3000,4000,9000])
s

0    1000
1    2000
2    3000
3    4000
4    9000
dtype: int64

In [23]:
s.mean()

np.float64(3800.0)

In [24]:
s.std()

3114.4823004794875

In [25]:
z_score=(s-s.mean())/s.std()
print(z_score)

0   -0.899026
1   -0.577945
2   -0.256865
3    0.064216
4    1.669619
dtype: float64


In [26]:
sn=StandardScaler().fit_transform(s.values.reshape(-1,1)) # standard deviation (n population data)
print(sn)

[[-1.00514142]
 [-0.64616234]
 [-0.28718326]
 [ 0.07179582]
 [ 1.86669121]]


In [27]:
data= {
    "temp": [30,32,34,35,36],
    "humidity":[40,39,34,28,27]
}
df=pd.DataFrame(data)
df


temp  humidity
0    30        40
1    32        39
2    34        34
3    35        28
4    36        27

In [28]:
norm_data=StandardScaler().fit_transform(df) # to standardize the code
n_df= pd.DataFrame(norm_data,columns=df.columns) # it gives the data in an array
norm_data

array([[-1.57841037,  1.18763139],
       [-0.64993368,  1.00206399],
       [ 0.27854301,  0.07422696],
       [ 0.74278135, -1.03917747],
       [ 1.2070197 , -1.22474487]])

In [ ]:
n_df