<a href="https://colab.research.google.com/github/gadichandu3-prog/inership_datadrame-_import/blob/main/numpy_day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
l=range(100)
%timeit [i**2 for i in l]# used to calculate the time for each iteration

8.57 µs ± 2.04 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Creating Arrays


In [5]:
a=np.array([1,2,3,4,5])
print(a.ndim)

1


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b.ndim)
print(b)

2
[[1 2 3]
 [4 5 6]]


In [7]:
c=np.array([[[1,2],[3,4],[5,6]]])
print(c.ndim)
print(c)

3
[[[1 2]
  [3 4]
  [5 6]]]


In [8]:
c=np.array([[[1,2],[2,3]],[[4,5],[6,7]]])
print(c)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]]


In [9]:
print(c.ndim)

3


In [10]:
print(c.shape)

(2, 2, 2)


In [11]:
print(a.shape)

(5,)


In [12]:
print(b.shape)

(2, 3)


Functions For Creating array


In [13]:
a=np.arange(1,10,2)# give the jump values
print(a)

[1 3 5 7 9]


In [14]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
a=np.eye(4,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [19]:
a=np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
print(np.diag(a))

[1 2 3 4]


Basic Data Types

In [21]:
a=np.arange(10)
print(a.dtype)

int64


In [22]:
a = np.arange(10,dtype="float64")
print(a.dtype)

float64


In [23]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


Other datatype

In [24]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [25]:
a=np.array([True,False])
print(a.dtype)

bool


In [26]:
a=np.array(["niha","Nihas"])
print(a.dtype) #unicode string type

<U5


Indexing and Slicing

In [27]:
a=np.arange(10)
print(a[5])

5


In [28]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [29]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [30]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [31]:
print(a[1:8:2])

[1 3 5 7]


In [32]:
a=np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

Copies and viewing

In [33]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [34]:
print(np.shares_memory(a,b))

True


In [35]:
b[0]=10 #viewing
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [36]:
a=np.arange(10)
b=a[::2].copy() #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [37]:
print(np.shares_memory(a,b))

False


Random number genarator

In [38]:
a=np.random.randint(0,20,15)
print(a)

[16 18 12  4 13 14  7  7  3  0 14  3 17 17 12]


In [40]:
mask=(a%2==0)

In [41]:
mask_a = a[mask]
print(mask_a)

[16 18 12  4 14  0 14 12]


In [42]:
a[mask]=-1
print(a)

[-1 -1 -1 -1 13 -1  7  7  3 -1 -1  3 17 17 -1]
